//generated by ResBuilder in 2023-10-16 16:22:38
#ifndef _RESULT_STR_INDEX_H_  
#define _RESULT_STR_INDEX_H_  

////StrResID Define Table////
#define  M26                       0   
#define  M27                       0   

#endif
