//generated by ResBuilder in 2023-08-01 17:12:53
#ifndef _RESULT_STR_INDEX_H_  
#define _RESULT_STR_INDEX_H_  

////StrResID Define Table////
#define  M26                       1   
#define  M27                       2   

#endif
