//generated by ResBuilder in 2023-05-07 22:59:59
#ifndef _RESULT_PIC_INDEX_H_
#define _RESULT_PIC_INDEX_H_

////BmpResID Define Table////

//PAGE 0
#define  PAGE0_4994_03_MENU_ICON_STATE_SEL    0x000001 //  images\03.menu_icon_state_sel.png
#define  PAGE0_de6b_04_MENU_ICON_HEART_SEL    0x000002 //  images\04.menu_icon_heart_sel.bmp
#define  PAGE0_4e97_04_MENU_ICON_HEART_SEL    0x000003 //  images\04.menu_icon_heart_sel.png
#define  PAGE0_5dad_05_MENU_ICON_BLOOD_SEL    0x000004 //  images\05.menu_icon_blood_sel.png
#define  PAGE0_060f_BIRD_1                    0x000005 //  images\bird_1.png
#define  PAGE0_18e2_CLOCK                     0x000006 //  images\clock.bmp
#define  PAGE0_7b17_COMPASS                   0x000007 //  images\compass.png
#define  PAGE0_daca_COMPASS1                  0x000008 //  images\compass1.png
#define  PAGE0_9d77_HOUR                      0x000009 //  images\hour.png
#define  PAGE0_976c_ICON1                     0x00000a //  images\icon1.png
#define  PAGE0_26a3_ICON2                     0x00000b //  images\icon2.png
#define  PAGE0_5fd9_MINUTE_SEC                0x00000c //  images\minute_sec.png
#define  PAGE0_38d6_SCA1                      0x00000d //  images\sca1.bmp
#define  PAGE0_8919_SCA2                      0x00000e //  images\sca2.bmp
#define  PAGE0_e65c_SCA3                      0x00000f //  images\sca3.bmp
#define  PAGE0_95e3_SCA5                      0x000010 //  images\sca5.bmp
#define  PAGE0_e4c4_TEST0                     0x000011 //  images\test0.jpg
#define  PAGE0_8b81_TEST1                     0x000012 //  images\test1.jpg
#define  PAGE0_3a4e_TEST2                     0x000013 //  images\test2.jpg
#define  PAGE0_550b_TEST3                     0x000014 //  images\test3.jpg
#define  PAGE0_5435_TEXT                      0x000015 //  images\text.png
#define  PAGE0_17d5_WEIXIN_20220507102155     0x000016 //  images\weixin_20220507102155.png
#define  PAGE0_97e0_WHITE                     0x000017 //  images\white.bmp

#endif

