//generated by ResBuilder in 2023-10-16 16:22:38
#ifndef _RESULT_PIC_INDEX_H_  
#define _RESULT_PIC_INDEX_H_  

////BmpResID Define Table////

//PAGE 0
#define  UI_CLOCKWISE_HOUR            0x000001 //  img\ARGB8565\clockwise_hour.png
#define  UI_CLOCKWISE_MIN             0x000002 //  img\ARGB8565\clockwise_min.png
#define  UI_CLOCKWISE_SEC             0x000003 //  img\ARGB8565\clockwise_sec.png

#endif
