/**
 * @copyright (c) 2003 - 2024, Goodix Co., Ltd. All rights reserved.
 *
 * @file    gh30x_demo_algo_memory.h
 *
 * @brief   GH30X algo memory set
 *
 * @version ref gh30x_example_common.h
 *
 */
#ifndef _GH30X_DEMO_ALGO_MEMORY_H_
#define _GH30X_DEMO_ALGO_MEMORY_H_

#include "gh30x_demo_algo_call.h"
#include "gh30x_demo_algo_config.h"

#if (__GOODIX_ALGO_CALL_MODE__)

#if __HBD_ALGORITHM_VERTION__ == __HBD_ALGORITHM_VERTION_TINY__
//hr
#define GH30X_HR_ALGORITHM_MEMORY_PEAK_1CHNL       (3212)       /**< HB 1 chnl algorithm peak memory size in byte */
#define GH30X_HR_ALGORITHM_MEMORY_RESIDENT_1CHNL   (2024)       /**< HB 1 chnl  algorithm desident memory size in byte */
#define GH30X_HR_ALGORITHM_MEMORY_REDUNDANCY       (100)
//spo2
#define GH30X_SPO2_ALGORITHM_MEMORY_PEAK_1CHNL     (3136)       /**< SPO2 1 chnl  algorithm peak memory size in byte */
#define GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_1CHNL (2432)       /**< SPO2 1 chnl  algorithm memory size in byte */
#define GH30X_SPO2_ALGORITHM_MEMORY_REDUNDANCY     (100)
//hrv
#define GH30X_HRV_ALGORITHM_MEMORY_PEAK            (3008)       /**< HRV algorithm peak memory size in byte */
#define GH30X_HRV_ALGORITHM_MEMORY_RESIDENT        (2844)       /**< HRV algorithm resident memory size in byte */
#define GH30X_HRV_ALGORITHM_MEMORY_REDUNDANCY      (100)
//nadt
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_PEAK       (3448)       /**< NADT algorithm peak memory size in byte */
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT   (3448)       /**< NADT algorithm resident memory size in byte */
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_REDUNDANCY  (100)

#elif  __HBD_ALGORITHM_VERTION__ == __HBD_ALGORITHM_VERTION_BASIC__
//hr
#define GH30X_HR_ALGORITHM_MEMORY_PEAK_1CHNL       (2084)       /**< HB 1 chnl algorithm peak memory size in byte */
#define GH30X_HR_ALGORITHM_MEMORY_RESIDENT_1CHNL   (1164)       /**< HB 1 chnl  algorithm desident memory size in byte */
#define GH30X_HR_ALGORITHM_MEMORY_REDUNDANCY       (100)
//spo2
#define GH30X_SPO2_ALGORITHM_MEMORY_PEAK_1CHNL     (2684)       /**< SPO2 1 chnl  algorithm peak memory size in byte */
#define GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_1CHNL (2100)       /**< SPO2 1 chnl  algorithm memory size in byte */
#define GH30X_SPO2_ALGORITHM_MEMORY_REDUNDANCY     (100)
//hrv
#define GH30X_HRV_ALGORITHM_MEMORY_PEAK            (3008)       /**< HRV algorithm peak memory size in byte */
#define GH30X_HRV_ALGORITHM_MEMORY_RESIDENT        (2844)       /**< HRV algorithm resident memory size in byte */
#define GH30X_HRV_ALGORITHM_MEMORY_REDUNDANCY      (100)
//nadt
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_PEAK       (1150)       /**< NADT algorithm peak memory size in byte */
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT   (1150)       /**< NADT algorithm resident memory size in byte */
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_REDUNDANCY (80)

#else
//hr
#define GH30X_HR_ALGORITHM_MEMORY_PEAK_1CHNL       (8708)       /**< HB 1 chnl algorithm peak memory size in byte */
#define GH30X_HR_ALGORITHM_MEMORY_RESIDENT_1CHNL   (3896)       /**< HB 1 chnl  algorithm desident memory size in byte */
#define GH30X_HR_ALGORITHM_MEMORY_REDUNDANCY       (100)
//spo2
#define GH30X_SPO2_ALGORITHM_MEMORY_PEAK_1CHNL     (7084)       /**< SPO2 1 chnl  algorithm peak memory size in byte */
#define GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_1CHNL (4308)       /**< SPO2 1 chnl  algorithm memory size in byte */
#define GH30X_SPO2_ALGORITHM_MEMORY_REDUNDANCY     (100)
//hrv
#define GH30X_HRV_ALGORITHM_MEMORY_PEAK            (3008)       /**< HRV algorithm peak memory size in byte */
#define GH30X_HRV_ALGORITHM_MEMORY_RESIDENT        (2844)       /**< HRV algorithm resident memory size in byte */
#define GH30X_HRV_ALGORITHM_MEMORY_REDUNDANCY      (100)
//nadt
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_PEAK       (3448)       /**< SOFT ADT algorithm peak memory size in byte */
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT   (3448)       /**< SOFT ADT algorithm resident memory size in byte */
#define GH30X_SOFT_ADT_ALGORITHM_MEMORY_REDUNDANCY (80)         /**< SOFT ADT algorithm redundancy memory size in byte */
#endif

/* algorithm mem config */
#if (__GOODIX_ALGO_CALL_MODE__)

#if (__USE_GOODIX_HR_ALGORITHM__)
#if __HR_ALGORITHM_SUPPORT_CHNL_NUM__ <= 1
#define   GH30X_ALGORITHM_HR_MEMORY_PEAK                    GH30X_HR_ALGORITHM_MEMORY_PEAK_1CHNL
#define   GH30X_ALGORITHM_HR_MEMORY_RESIDENT                GH30X_HR_ALGORITHM_MEMORY_RESIDENT_1CHNL
#elif __HR_ALGORITHM_SUPPORT_CHNL_NUM__ == 2
#define   GH30X_ALGORITHM_HR_MEMORY_PEAK                    GH30X_HR_ALGORITHM_MEMORY_PEAK_2CHNL
#define   GH30X_ALGORITHM_HR_MEMORY_RESIDENT                GH30X_HR_ALGORITHM_MEMORY_RESIDENT_2CHNL
#elif __HR_ALGORITHM_SUPPORT_CHNL_NUM__ == 3
#define   GH30X_ALGORITHM_HR_MEMORY_PEAK                    GH30X_HR_ALGORITHM_MEMORY_PEAK_3CHNL
#define   GH30X_ALGORITHM_HR_MEMORY_RESIDENT                GH30X_HR_ALGORITHM_MEMORY_RESIDENT_3CHNL
#elif __HR_ALGORITHM_SUPPORT_CHNL_NUM__ >= 4
#define   GH30X_ALGORITHM_HR_MEMORY_PEAK                    GH30X_HR_ALGORITHM_MEMORY_PEAK_4CHNL
#define   GH30X_ALGORITHM_HR_MEMORY_RESIDENT                GH30X_HR_ALGORITHM_MEMORY_RESIDENT_4CHNL
#endif
#define GH30X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT    (GH30X_ALGORITHM_HR_MEMORY_PEAK - GH30X_ALGORITHM_HR_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_HR_MEMORY_REDUNDANCY               (GH30X_HR_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_HR_MEMORY_RESIDENT                 (0)
#define GH30X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH30X_ALGORITHM_HR_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_HSM_ALGORITHM__)
#define   GH30X_ALGORITHM_HSM_MEMORY_RESIDENT              (GH30X_HSM_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT   (GH30X_HSM_ALGORITHM_MEMORY_PEAK - GH30X_HSM_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_HSM_MEMORY_REDUNDANCY              (GH30X_HSM_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_HSM_MEMORY_RESIDENT   (0)
#define GH30X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT   (0)
#define GH30X_ALGORITHM_HSM_MEMORY_REDUNDANCY              (0)
#endif

#if (__USE_GOODIX_SPO2_ALGORITHM__)
#if __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ <= 1
#define   GH30X_ALGORITHM_SPO2_MEMORY_PEAK                 GH30X_SPO2_ALGORITHM_MEMORY_PEAK_1CHNL
#define   GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT             GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_1CHNL
#elif __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ == 2
#define   GH30X_ALGORITHM_SPO2_MEMORY_PEAK                 GH30X_SPO2_ALGORITHM_MEMORY_PEAK_2CHNL
#define   GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT             GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_2CHNL
#elif __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ == 3
#define   GH30X_ALGORITHM_SPO2_MEMORY_PEAK                 GH30X_SPO2_ALGORITHM_MEMORY_PEAK_3CHNL
#define   GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT             GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_3CHNL
#elif __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ >= 4
#define   GH30X_ALGORITHM_SPO2_MEMORY_PEAK                 GH30X_SPO2_ALGORITHM_MEMORY_PEAK_4CHNL
#define   GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT             GH30X_SPO2_ALGORITHM_MEMORY_RESIDENT_4CHNL
#endif
#define GH30X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT  (GH30X_ALGORITHM_SPO2_MEMORY_PEAK - GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_SPO2_MEMORY_REDUNDANCY             (GH30X_SPO2_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT               (0)
#define GH30X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT  (0)
#define GH30X_ALGORITHM_SPO2_MEMORY_REDUNDANCY             (0)
#endif

#if (__USE_GOODIX_ECG_ALGORITHM__)
#define   GH30X_ALGORITHM_ECG_MEMORY_RESIDENT              (GH30X_ECG_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT   (GH30X_ECG_ALGORITHM_MEMORY_PEAK - GH30X_ECG_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_ECG_MEMORY_REDUNDANCY              (GH30X_ECG_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_ECG_MEMORY_RESIDENT                (0)
#define GH30X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT   (0)
#define GH30X_ALGORITHM_ECG_MEMORY_REDUNDANCY              (0)
#endif

#if (__USE_GOODIX_HRV_ALGORITHM__)
#define   GH30X_ALGORITHM_HRV_MEMORY_RESIDENT              (GH30X_HRV_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT   (GH30X_HRV_ALGORITHM_MEMORY_PEAK - GH30X_HRV_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_HRV_MEMORY_REDUNDANCY              (GH30X_HRV_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_HRV_MEMORY_RESIDENT                (0)
#define GH30X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT   (0)
#define GH30X_ALGORITHM_HRV_MEMORY_REDUNDANCY              (0)
#endif

#if (__USE_GOODIX_BT_ALGORITHM__)
#define   GH30X_ALGORITHM_BT_MEMORY_RESIDENT               (GH30X_BT_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT    (GH30X_BT_ALGORITHM_MEMORY_PEAK - GH30X_BT_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_BT_MEMORY_REDUNDANCY               (GH30X_BT_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_BT_MEMORY_RESIDENT                 (0)
#define GH30X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH30X_ALGORITHM_BT_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_RESP_ALGORITHM__)
#define   GH30X_ALGORITHM_RESP_MEMORY_RESIDENT             (GH30X_RESP_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT  (GH30X_RESP_ALGORITHM_MEMORY_PEAK - GH30X_RESP_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_RESP_MEMORY_REDUNDANCY             (GH30X_RESP_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_RESP_MEMORY_RESIDENT               (0)
#define GH30X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT  (0)
#define GH30X_ALGORITHM_RESP_MEMORY_REDUNDANCY             (0)
#endif

#if (__USE_GOODIX_AF_ALGORITHM__)
#define   GH30X_ALGORITHM_AF_MEMORY_RESIDENT               (GH30X_AF_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT    (GH30X_AF_ALGORITHM_MEMORY_PEAK - GH30X_AF_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_AF_MEMORY_REDUNDANCY               (GH30X_AF_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_AF_MEMORY_RESIDENT                 (0)
#define GH30X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH30X_ALGORITHM_AF_MEMORY_REDUNDANCY               (0)
#endif


#if (__USE_GOODIX_SOFT_ADT_ALGORITHM__)
#define   GH30X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT              (GH30X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT   (GH30X_SOFT_ADT_ALGORITHM_MEMORY_PEAK - GH30X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY              (GH30X_SOFT_ADT_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT                (0)
#define GH30X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT   (0)
#define GH30X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY              (0)
#endif

#if (__USE_GOODIX_BP_ALGORITHM__)
#define   GH30X_ALGORITHM_BP_MEMORY_RESIDENT                    (GH30X_BP_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_BP_MEMORY_PEAK_WITHOUT_RESIDENT         (GH30X_BP_ALGORITHM_MEMORY_PEAK - GH30X_BP_ALGORITHM_MEMORY_RESIDENT)
#define GH30X_ALGORITHM_BP_MEMORY_REDUNDANCY                    (GH30X_BP_ALGORITHM_MEMORY_REDUNDANCY)
#else
#define GH30X_ALGORITHM_BP_MEMORY_RESIDENT                      (0)
#define GH30X_ALGORITHM_BP_MEMORY_PEAK_WITHOUT_RESIDENT         (0)
#define GH30X_ALGORITHM_BP_MEMORY_REDUNDANCY                    (0)
#endif

#endif

#ifndef GH30X_ALGO_FUNCTION_GROUP_0
#error GH30X_ALGO_FUNCTION_GROUP_0 no def
#endif
#ifndef GH30X_ALGO_FUNCTION_GROUP_1
#error GH30X_ALGO_FUNCTION_GROUP_1 no def
#endif
#ifndef GH30X_ALGO_FUNCTION_GROUP_2
#error GH30X_ALGO_FUNCTION_GROUP_2 no def
#endif
#ifndef GH30X_ALGO_FUNCTION_GROUP_3
#error GH30X_ALGO_FUNCTION_GROUP_3 no def
#endif

#define MAX(a, b) (((a) > (b)) ? (a) : (b))
#define GH30X_ALGORITHMS_MEMORY_(X) (((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_HR   )) * __USE_GOODIX_HR_ALGORITHM__      * GH30X_ALGORITHM_HR_MEMORY_RESIDENT                      ) +   \
                                      ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_SPO2    )) * __USE_GOODIX_SPO2_ALGORITHM__     * GH30X_ALGORITHM_SPO2_MEMORY_RESIDENT               ) +   \
                                      ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_HRV     )) * __USE_GOODIX_HRV_ALGORITHM__      * GH30X_ALGORITHM_HRV_MEMORY_RESIDENT                ) +   \
                                      ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_SOFT_ADT)) * __USE_GOODIX_SOFT_ADT_ALGORITHM__ * GH30X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT           ) +   \
                                      MAX(MAX(MAX(((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_HR  )) * __USE_GOODIX_HR_ALGORITHM__  * GH30X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT  ) +  \
                                        ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_HR  )) * __USE_GOODIX_HR_ALGORITHM__  * GH30X_ALGORITHM_HR_MEMORY_REDUNDANCY                       ),   \
                                      ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_SPO2    )) * __USE_GOODIX_SPO2_ALGORITHM__     * GH30X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT   ) +  \
                                        ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_SPO2    )) * __USE_GOODIX_SPO2_ALGORITHM__     * GH30X_ALGORITHM_SPO2_MEMORY_REDUNDANCY            )),  \
                                      ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_HRV     )) * __USE_GOODIX_HRV_ALGORITHM__      * GH30X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT    ) +  \
                                        ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_HRV     )) * __USE_GOODIX_HRV_ALGORITHM__      * GH30X_ALGORITHM_HRV_MEMORY_REDUNDANCY             )),  \
                                      ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_SOFT_ADT)) * __USE_GOODIX_SOFT_ADT_ALGORITHM__    * GH30X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT) + \
                                        ((0 != (GH30X_ALGO_FUNCTION_GROUP_##X & GH30X_FUNCTION_SOFT_ADT)) * __USE_GOODIX_SOFT_ADT_ALGORITHM__ * GH30X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY        )))

//memory resident
#define GH30X_ALGORITHMS_MEMORY  (0)
#if GH30X_ALGORITHMS_MEMORY < GH30X_ALGORITHMS_MEMORY_(0)
#undef GH30X_ALGORITHMS_MEMORY
#define GH30X_ALGORITHMS_MEMORY GH30X_ALGORITHMS_MEMORY_(0)
#endif
#if GH30X_ALGORITHMS_MEMORY < GH30X_ALGORITHMS_MEMORY_(1)
#undef GH30X_ALGORITHMS_MEMORY
#define GH30X_ALGORITHMS_MEMORY GH30X_ALGORITHMS_MEMORY_(1)
#endif
#if GH30X_ALGORITHMS_MEMORY < GH30X_ALGORITHMS_MEMORY_(2)
#undef GH30X_ALGORITHMS_MEMORY
#define GH30X_ALGORITHMS_MEMORY GH30X_ALGORITHMS_MEMORY_(2)
#endif
#if GH30X_ALGORITHMS_MEMORY < GH30X_ALGORITHMS_MEMORY_(3)
#undef GH30X_ALGORITHMS_MEMORY
#define GH30X_ALGORITHMS_MEMORY GH30X_ALGORITHMS_MEMORY_(3)
#endif
#if GH30X_ALGORITHMS_MEMORY < GH30X_ALGORITHMS_MEMORY_(4)
#undef GH30X_ALGORITHMS_MEMORY
#define GH30X_ALGORITHMS_MEMORY GH30X_ALGORITHMS_MEMORY_(4)
#endif

//final size
#define GH30X_ALGORITHMS_MEMORY_SIZE_FINAL (((GU32)((GH30X_ALGORITHMS_MEMORY + 3) / 4)) * 4)

/**
 * @fn     GS8 GH30X_AlgoMemConfig( GU32 unMemSize)
 *
 * @brief  Config algorithm memory.
 *
 * @attention   Mem can only be static,such as global array
 *
 * @param[in]  unMemSize       memory size(unit:byte)
 *
 * @return  error code
 * @retval  #GH30X_RET_OK                      return successfully
 * @retval  #GH30X_RET_RESOURCE_ERROR          return algorithm mem config error
 */
GS8 GH30X_AlgoMemConfig( GU32 unMemSize);

#endif

#endif /* _GH30X_DEMO_ALGO_MEMORY_H_ */

/********END OF FILE********* Copyright (c) 2003 - 2024, Goodix Co., Ltd. ********/
